FROM java:8
VOLUME /tmp
ADD poc-0.0.1-SNAPSHOT.jar app.jar
ADD wait-for-it.sh wait-for-it.sh
RUN chmod +x '/wait-for-it.sh'
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["./wait-for-it.sh", "null:0000","-t","30","--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","--hostname=cbdb","--bucket=default","--password"]